### ISSUE TITLE
Expose font baseline info

### ISSUE THREAD

**Issue by acowley** [Twinside/FontyFruity#11]
I reported an [issue](https://github.com/timbod7/haskell-chart/issues/65) in Chart that is due to a [limitation](https://github.com/diagrams/diagrams-rasterific/issues/21) of the `diagrams-rasterific` backend. My understanding is that `diagrams` wants the origin Y coordinate of some text to be the baseline height of the rendered text, `FontyFruity` exposes the full string bounding box, and `Rasterific`'s `printTextAt` takes the desired baseline height. I think, then, the issue is that it is not clear how to locate the bounding box returned by `stringBoundingBox` with respect to the baseline height given to `printTextAt`. What is needed to improve diagrams compatibility is the difference between the top of the bounding box and the baseline.

Thanks for any assistance!

**Comment by Twinside** [comment]
Noted, I'll look into it
