### ISSUE TITLE
Sometimes adding characters reduces the height of the bounding box

### ISSUE THREAD

**Issue by schell** [Twinside/FontyFruity#13]
According to `stringBoundingBox` the string "I am a pretty long string" has a bounding box that is smaller in height than the string "I am a pretty long string-". It seems that adding the last '-' character is causing `stringBoundingBox` to return a larger _yMin, which in turn makes the height smaller. Here are some renderings of the strings along with their bounding boxes (in white).

![screenshot 2015-06-02 17 40 24](https://cloud.githubusercontent.com/assets/24942/7950373/7f9badc6-094e-11e5-9409-90be2c4e0e44.png)

![screenshot 2015-06-02 17 42 29](https://cloud.githubusercontent.com/assets/24942/7950386/c16d1a96-094e-11e5-85da-588c37668693.png)

**Comment by Twinside** [comment]
Does this happen on all the fonts or just one in specific?

**Comment by schell** [comment]
I'll check. Currently this is happening with Arial, 16 point.

**Comment by schell** [comment]
Tahoma, 16 point:
![screenshot 2015-06-03 10 04 03](https://cloud.githubusercontent.com/assets/24942/7966285/f39b4b9e-09d7-11e5-90e4-4240b632cc37.png)

**Comment by schell** [comment]
Lol, in the last one you can see my inadequate polygon stenciling :)

**Comment by schell** [comment]
It also increases the width of the bounding box, which makes sense. Any idea why the bounding boxes seem to bee too wide?

**Comment by Twinside** [comment]
Sorry for the delay, I may have an idea, but I'm busy right now, I hope to have time to look after it this week-end.

**Comment by Twinside** [comment]
Is this fixed?

**Comment by schell** [comment]
It seems to be - both the width and the height seem to be correct.
<img width="284" alt="screenshot 2016-01-05 14 09 35" src="https://cloud.githubusercontent.com/assets/24942/12129041/fb7ca0aa-b3b5-11e5-93c6-48edee347ca9.png">
:+1:
