### ISSUE TITLE
Support GHC 8.8

### ISSUE THREAD

**Issue by lancelet** [Twinside/FontyFruity#26]
GHC 8.8 implements the final part of the [`MonadFail` proposal](https://wiki.haskell.org/MonadFail_Proposal). The impact of this on `FontyFruity` is that the `put` method can no longer call `fail` to indicate that `put` is not implemented. (In turn because `Data.Binary.Put.Put` does not implement a `MonadFail` instance.)

I have raised PR #25 that addresses this issue by replacing `fail` with `error`.

I'm willing to have a go at implementing any alternative solution if this approach is not acceptable.

**Comment by Twinside** [comment]
PR merged
